### ISSUE TITLE
Need for further configuration property

### ISSUE THREAD

**Issue by SteinerPascal** [SteinerPascal/sparnatural-port#29]
Hi @tfrancart ,
I'm having some difficulties with the sparql generation of the new mapwidget. I would like to get the following SPARQL:
```
select * where { 
  ?Tree_1 rdf:type <http://dbpedia.org/ontology/Tree>.
  ?Tree_1 <http://www.opengis.net/ont/geosparql#hasGeometry> ?geomA.
  ?geomA <http://www.opengis.net/ont/geosparql#asWKT> ?aWKT.
  VALUES ?Area_2 {
'''<http://www.opengis.net/def/crs/OGC/1.3/CRS84> \n        Polygon(( 46.13845231463026 6.093871593475343, 46.282902242821145 6.093871593475343, 46.282902242821145 6.302611827850342, 46.13845231463026 6.302611827850342, 46.13845231463026 6.093871593475343))\n        '''^^<http://www.opengis.net/ont/geosparql#wktLiteral>
  }
  FILTER(<http://www.opengis.net/def/function/geosparql/sfWithin>(?aWKT, ?Area_2))
} limit 100 

```
This gives me back all the trees within a certain area, where the ?Tree_1 is the subject and the ?Area_2 is the selected value in the mapwidget.

The problem is, currently this query is not possible. I can only create queries with a predicate triple connecting the subject triple and object triple. Like this:
```
?Tree_1 rdf:type <http://dbpedia.org/ontology/Tree>;
    <http://www.opengis.net/ont/geosparql#withinArea> ?Area_2.
  ?Tree_1 <http://www.opengis.net/ont/geosparql#hasGeometry> ?geomA.
  ?geomA <http://www.opengis.net/ont/geosparql#asWKT> ?aWKT.
  VALUES ?Area_2 {
    '''<http://www.opengis.net/def/crs/OGC/1.3/CRS84> \n    Polygon(( 46.1937350184355 6.107867360115051, 46.22295888245306 6.107867360115051, 46.22295888245306 6.1825400590896615, 46.1937350184355 6.1825400590896615, 46.1937350184355 6.107867360115051))\n    '''^^<http://www.opengis.net/ont/geosparql#wktLiteral>
  }
  FILTER(<http://www.opengis.net/def/function/geosparql/sfWithin>(?aWKT, ?Area_2))
```
Note: I don't want the second line ` <http://www.opengis.net/ont/geosparql#whithinArea> ?Area_2.` Since there is actually no connection between them (at least in the knowledge graph, they have no possible predicate connecting them)

Have you already dealt with such a query? My proposal would be to introduce a config for the mapwidget (or generally similar functions ) where there is actually no property connecting the subject and literal object. But only a function connecting them.

Currently, I'm just doing a check if the value comes from the mapwidget and if so then don't create the predicate tripple. And that's done in the code and not in the config somewhere.

**Comment by SteinerPascal** [comment]
Thanks for the suggested query with the propertypath. That is indeed already an improvement. 

For the intermediate variables: I need only the ?Area_2 in the select clause. The ?geomA  i don't need.

Regarding your suggestion to change the **area** to **geometry**: Yes that's very interesting and definitely better. This way i can also just do something like:
```
select ?Tree_1 ?aWKT where { 
  ?Tree_1 rdf:type <http://dbpedia.org/ontology/Tree>.
OPTIONAL{
  ?Tree_1 <http://www.opengis.net/ont/geosparql#hasGeometry>/<http://www.opengis.net/ont/geosparql#asWKT> ?aWKT.
 }
} limit 100 
```
To just optionally show the location if they have one.

So that means in order to get the location of the ?Tree_1 inside an area I would need the following:
?Tree hasGeometry ?aWKT.
WHERE
?aWKT isWithin ?Area

SPARQL example:
```
select ?Tree_1 ?aWKT ?Area_2 where { 
?Tree_1 rdf:type <http://dbpedia.org/ontology/Tree>.
?Tree_1 <http://www.opengis.net/ont/geosparql#hasGeometry>/<http://www.opengis.net/ont/geosparql#asWKT> ?aWKT.
 # whereaction clicked by the user
?aWKT  <http://www.opengis.net/ont/geosparql#withinArea> ?Area_2. # Same problem?
```
Seems somehow i have pushed the problem just a bit further away? Or do you have an additional solution?

I would also prefer a solution where we don't have to touch the config. But mabe you can introduce an emptySPARQL string config property? If this property is set, then no SPARQL triple is created?

**Comment by tfrancart** [comment]
> For the intermediate variables: I need only the ?Area_2 in the select clause. The ?geomA i don't need.

That's strange. Why do you need it since this is the value that is bound by whatever value is drawn in the widget ? (with the VALUES clause in your first query - if I understand correctly).

But I am still not sure to understand the problem. Assuming the query with the property path is what you need:

```
select * where { 
  ?Tree_1 rdf:type <http://dbpedia.org/ontology/Tree>.
  ?Tree_1 <http://www.opengis.net/ont/geosparql#hasGeometry>/<http://www.opengis.net/ont/geosparql#asWKT> ?aWKT.
  FILTER(<http://www.opengis.net/def/function/geosparql/sfWithin>(?aWKT, '''<http://www.opengis.net/def/crs/OGC/1.3/CRS84> \n        Polygon(( ...))\n        '''^^<http://www.opengis.net/ont/geosparql#wktLiteral>))
} limit 100 
```

Then what you need in Sparnatural is a one-line criteria "Tree within Area", with property "within" configured as a MapWidget. And that MapWidget will generate all the part of the query in the Filter : `  FILTER(<http://www.opengis.net/def/function/geosparql/sfWithin>(?aWKT, '''<http://www.opengis.net/def/crs/OGC/1.3/CRS84> \n        Polygon(( ...))\n        '''^^<http://www.opengis.net/ont/geosparql#wktLiteral>))`

Please tell me what I am missing...
